# Workflow executed on "push" events.
name: push

on: push

jobs:

  # Run tests in Maven.
  test:
    runs-on: ubuntu-latest

    container:
      image: maven:3.6-alpine

    steps:

      # Retrieve the code from Github.
      # Use branch "v2" of the "checkout" plugin
      - uses: actions/checkout@v2
        
      - name: Execute tests with Maven.
        run: mvn -B clean test
